export function placeholderImg(w, h, color, label) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><rect width="100%" height="100%" fill="${color}20"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="${color}80" font-family="sans-serif" font-size="14">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

export const MOCK_POSTS = [
  {
    id: "p1", app_id: "1", type: "bug", status: "new",
    title: "CSV export truncates long field names",
    body: "When exporting the season summary to CSV, any column header over 30 characters gets cut off. This breaks downstream imports into Google Sheets. Tested on Chrome 122 and Firefox 124.",
    author_name: "Marcus", author_email: "marcus@example.com",
    upvote_count: 14, tags: ["export", "csv"], created_at: "2026-02-28T10:30:00Z",
    images: [placeholderImg(400, 240, "#ef4444", "screenshot.png")],
    poll: null,
  },
  {
    id: "p2", app_id: "1", type: "feature", status: "planned",
    title: "Add expected goals (xG) column to match reports",
    body: "Would love to see xG data alongside actual goals scored. This is the most requested stat in modern football analytics.",
    author_name: "Sasha", author_email: "sasha@example.com",
    upvote_count: 31, tags: ["stats", "xG"], created_at: "2026-02-25T14:00:00Z",
    images: [],
    poll: {
      question: "Which xG provider should we use?",
      options: [
        { id: "o1", label: "StatsBomb", votes: 18 },
        { id: "o2", label: "Understat", votes: 12 },
        { id: "o3", label: "FBref / Opta", votes: 9 },
      ],
    },
  },
  {
    id: "p3", app_id: "2", type: "feature", status: "reviewing",
    title: "Toggle between satellite and street view",
    body: "It would be great to switch the base map layer to satellite view so you can see how the buildings sit in their actual landscape context.",
    author_name: "Anonymous", author_email: null,
    upvote_count: 8, tags: ["map", "layers"], created_at: "2026-02-27T09:15:00Z",
    images: [],
    poll: null,
  },
  {
    id: "p4", app_id: "2", type: "bug", status: "in_progress",
    title: "Popup info cards overlap on mobile",
    body: "On iPhone 14 Pro, tapping a building marker opens the info card but it extends off the right edge of the screen. Can't read the full description or see the photo.",
    author_name: "Jordan", author_email: "jordan@design.co",
    upvote_count: 5, tags: ["mobile", "responsive"], created_at: "2026-02-26T16:45:00Z",
    images: [
      placeholderImg(400, 240, "#3b82f6", "mobile-bug-1.png"),
      placeholderImg(400, 240, "#3b82f6", "mobile-bug-2.png"),
    ],
    poll: null,
  },
  {
    id: "p5", app_id: "3", type: "feature", status: "new",
    title: "Add sound effects for countdown milestones",
    body: "A subtle chime or animation when the countdown hits 30 days, 7 days, 1 day, etc. would make it more engaging to check.",
    author_name: "DevFan", author_email: null,
    upvote_count: 22, tags: ["audio", "ux"], created_at: "2026-03-01T08:00:00Z",
    images: [],
    poll: {
      question: "What kind of effect do you prefer?",
      options: [
        { id: "o4", label: "Sound chime", votes: 11 },
        { id: "o5", label: "Confetti animation", votes: 15 },
        { id: "o6", label: "Both", votes: 8 },
        { id: "o7", label: "Keep it simple, no effects", votes: 3 },
      ],
    },
  },
  {
    id: "p6", app_id: "1", type: "general", status: "done",
    title: "Love the new dark mode",
    body: "Just wanted to say the dark theme is really well done. The warm blacks look great and the contrast is perfect for late-night stats checking.",
    author_name: "NightOwl", author_email: "nightowl@mail.com",
    upvote_count: 19, tags: ["dark-mode", "praise"], created_at: "2026-02-20T22:00:00Z", completed_at: "2026-02-24T10:00:00Z",
    images: [],
    poll: null,
  },
  {
    id: "p7", app_id: "3", type: "bug", status: "new",
    title: "Countdown shows wrong time in UTC+5 timezone",
    body: "I'm in Pakistan and the countdown is about 5 hours ahead. Seems like it's not converting from the match kickoff timezone correctly.",
    author_name: "Hamza", author_email: "hamza@dev.pk",
    upvote_count: 7, tags: ["timezone", "bug"], created_at: "2026-03-02T05:30:00Z",
    images: [placeholderImg(400, 240, "#f59e0b", "tz-comparison.png")],
    poll: null,
  },
  {
    id: "p8", app_id: "2", type: "feature", status: "planned",
    title: "Walking tour route mode",
    body: "Let users plot a route between multiple FLW buildings and get walking directions. Would be amazing for architecture tours.",
    author_name: "ArchWalker", author_email: "arch@walker.io",
    upvote_count: 27, tags: ["routes", "tour"], created_at: "2026-02-22T11:20:00Z",
    images: [],
    poll: {
      question: "How should route stops be ordered?",
      options: [
        { id: "o8", label: "Chronological (year built)", votes: 14 },
        { id: "o9", label: "Shortest walking distance", votes: 21 },
        { id: "o10", label: "User's custom order", votes: 10 },
      ],
    },
  },
  {
    id: "p9", app_id: "1", type: "bug", status: "declined",
    title: "Page doesn't load in Internet Explorer",
    body: "I tried opening the report in IE11 and it's completely blank.",
    author_name: "OldSchool", author_email: null,
    upvote_count: 1, tags: ["browser"], created_at: "2026-02-15T09:00:00Z",
    images: [],
    poll: null,
  },
  {
    id: "p10", app_id: "3", type: "general", status: "reviewing",
    title: "Widget embed for forums and blogs",
    body: "Would be cool to embed the countdown as a small widget on Arsenal fan forums or personal blogs. Maybe an iframe snippet or web component.",
    author_name: "BloggerFC", author_email: "blogger@fc.net",
    upvote_count: 16, tags: ["embed", "widget"], created_at: "2026-02-23T17:40:00Z",
    images: [],
    poll: null,
  },
  {
    id: "p11", app_id: "2", type: "general", status: "done",
    title: "Added Fallingwater interior photos",
    body: "Thanks for adding the interior shots to Fallingwater — it really helps to see how the cantilevers work from inside.",
    author_name: "StructuralFan", author_email: null,
    upvote_count: 11, tags: ["content", "photos"], created_at: "2026-02-10T13:00:00Z", completed_at: "2026-02-18T09:00:00Z",
    images: [
      placeholderImg(400, 240, "#10b981", "fallingwater-1.jpg"),
      placeholderImg(400, 240, "#10b981", "fallingwater-2.jpg"),
      placeholderImg(400, 240, "#10b981", "fallingwater-3.jpg"),
    ],
    poll: null,
  },
  {
    id: "p12", app_id: "1", type: "feature", status: "in_progress",
    title: "Season comparison overlay chart",
    body: "A line chart overlaying this season's points progression vs. last season. Toggle-able per competition.",
    author_name: "DataViz", author_email: "dataviz@analytics.co",
    upvote_count: 24, tags: ["charts", "comparison"], created_at: "2026-02-18T10:00:00Z",
    images: [],
    poll: null,
  },
];
